# Build & deploy to Cloud Run in europe-west2 (London)
# Project: payslip-web-v1 (44689628415)
# Service: payslip-web

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/payslip-web-v1/payslip-web/payslip-web:${COMMIT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west2-docker.pkg.dev/payslip-web-v1/payslip-web/payslip-web:${COMMIT_SHA}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'payslip-web'
      - '--image'
      - 'europe-west2-docker.pkg.dev/payslip-web-v1/payslip-web/payslip-web:${COMMIT_SHA}'
      - '--region'
      - 'europe-west2'
      - '--project'
      - 'payslip-web-v1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--cpu'
      - '2'
      - '--memory'
      - '1Gi'
      - '--max-instances'
      - '3'
      - '--timeout'
      - '900'

images:
  - 'europe-west2-docker.pkg.dev/payslip-web-v1/payslip-web/payslip-web:${COMMIT_SHA}'
